framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        enabled: true
        auto_mapping:
           App\Entity\: true 

when@test:
    framework:
        validation:
            not_compromised_password: false
