vich_uploader:
    db_driver: orm

    mappings:
       uploads:
           uri_prefix: /uploads
           upload_destination: '%kernel.project_dir%/public/uploads'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y/m/d'
                    date_time_property: updatedAt